title: Wanderland Travelers
logo: <img src="/images/logo.png" />
email: hello@wanderlandtravelers.com
description: Always keep moving, but not too fast
baseurl: ''
url: 'http://wanderlandtravelers.com'
header-img: P2220639web.jpg
menu:
  - id: home
    name: Home
    url: /
  - id: sample-page
    name: Sample Page
    url: /sample-page
  - id: contact
    name: Contact
    url: /contact
banner-title: Wanderland Travelers
banner-desc: null
author-pic: face.jpg
author-name: null
about-author: null
phone: (496)-169-6557
website: 'https://dwayne.example.com'
google_url: null
twitter_url: null
instagram_url: null
pinterest_url: null
dribbble_url: null
facebook_url: null
discus_identifier: http-wanderlandtravelers-com
mailchimp: null
analytics: null
paginate: 12
paginate_path: '/page:num/'
markdown: kramdown
plugins:
  - jekyll-admin
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-youtube
include:
  - _pages
