title: Wanderland Travelers
logo: <img src="/images/logo.png" />
email: hello@wanderlandtravelers.com
description: Always keep moving, but not too fast
baseurl: ''
url: 'http://wanderlandtravelers.com'
header-img: DSC_1725.jpg
defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "maggie"
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
collections:
  authors:
    output: true
    permalink: /author/:name/index
menu:
  - id: home
    name: Home
    url: /
  - id: say-thanks
    name: Say Thanks
    url: https://ko-fi.com/wanderlandtravelers
  - id: about-us
    name: About Us
    url: /about/
permalink: pretty
banner-title: Wanderland Travelers
banner-desc: null
author-pic: face.jpg
author-name: null
about-author: null
phone: (496)-169-6557
website: 'https://dwayne.example.com'
google_url: null
twitter_url: null
instagram_url: null
pinterest_url: null
dribbble_url: null
facebook_url: null
discus_identifier: http-wanderlandtravelers-com
mailchimp: null
analytics: null
paginate: 12
paginate_path: '/page:num/'
markdown: kramdown
plugins:
  - jekyll-admin
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-youtube
include:
  - _pages
