title: Wanderland Travelers
logo: <img src="/images/logo.png" />
email: hello@wanderlandtravelers.com
description: Always keep moving, but not too fast
baseurl: ''
url: 'https://wanderlandtravelers.com'
carousel_images:
  - file: 1.Monuments.jpg
    alt: Panoramic view of monument valley
  - file: 2.FendyAZ.jpg
    alt: Fendy in Arizona
  - file: 3.Cacti.jpg
    alt: Epic cacti
  - file: 4.FendyPastels.jpg
    alt: Fendy with beautiful pastels in the sky above
  - file: 5.SealRock.jpg
    alt: Enjoying seal rock
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "maggie"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
collections:
  authors:
    output: true
  author_snippets:
    output: false
menu:
  - id: home
    name: Home
    url: /
  - id: say-thanks
    name: Say Thanks
    url: https://ko-fi.com/wanderlandtravelers
  - id: about-us
    name: About Us
    url: /about/
permalink: /:year/:month/:day/:title/
banner-title: Wanderland Travelers
banner-desc: null
author-pic: face.jpg
author-name: null
about-author: null
phone: (496)-169-6557
website: 'https://dwayne.example.com'
google_url: null
twitter_url: null
instagram_url: null
pinterest_url: null
dribbble_url: null
facebook_url: null
discus_identifier: http-wanderlandtravelers-com
mailchimp: null
analytics: 'UA-78209422-2'
paginate: 12
paginate_path: '/page:num/'
markdown: kramdown
jekyll-archives:
  enabled:
    - categories
    - year
    - month
    - tags
  layouts:
    category: category-archive
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    category: '/category/:name/'
jekyll_search_url_blacklist:
  - /
  - /404.html
  - /feed.xml
  - /robots.txt
  - /sitemap.xml
  - /search.json
  - /search/
  - /author_snippets/maggie/
plugins:
  - jekyll-admin
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-youtube
include:
  - _pages
exclude:
  - bin
  - src
  - gulpfile.js
  - changelog.txt
  - screenshot.png
  - LICENSE-layout.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - vendor
